"""
World Simulator for StoryLab.

Proactively generates events from world state tensions and resolves cascades.
"""

from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import random
import math


class TensionType(str, Enum):
    """Types of world tensions."""
    RESOURCE_SCARCITY = "resource_scarcity"
    POWER_IMBALANCE = "power_imbalance"
    TERRITORIAL_DISPUTE = "territorial_dispute"
    IDEOLOGICAL_CONFLICT = "ideological_conflict"
    POPULATION_PRESSURE = "population_pressure"
    ALLIANCE_FRACTURE = "alliance_fracture"
    PENDING_CONFLICT = "pending_conflict"
    UNRESOLVED_EVENT = "unresolved_event"


@dataclass
class Tension:
    """A detected tension in the world state."""
    tension_id: str
    tension_type: TensionType
    description: str
    entities_involved: List[str]
    severity: float
    contributing_factors: List[str]
    potential_events: List[str]
    detected_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    def to_dict(self) -> Dict:
        return {
            'tension_id': self.tension_id,
            'tension_type': self.tension_type.value,
            'description': self.description,
            'entities_involved': self.entities_involved,
            'severity': self.severity,
            'contributing_factors': self.contributing_factors,
            'potential_events': self.potential_events,
            'detected_at': self.detected_at,
        }


@dataclass
class CascadeStep:
    """A step in an event cascade."""
    step_id: str
    trigger_event_id: str
    resulting_event_id: str
    propagation_type: str
    affected_entities: List[str]
    delay_generations: int
    resolved: bool = False
    
    def to_dict(self) -> Dict:
        return {
            'step_id': self.step_id,
            'trigger_event_id': self.trigger_event_id,
            'resulting_event_id': self.resulting_event_id,
            'propagation_type': self.propagation_type,
            'affected_entities': self.affected_entities,
            'delay_generations': self.delay_generations,
            'resolved': self.resolved,
        }


@dataclass
class SimulatedEvent:
    """An event generated by the world simulator."""
    event_id: str
    name: str
    event_type: str
    description: str
    causes: List[str]
    affected_entities: List[str]
    expected_consequences: List[str]
    generation: int
    resolved: bool = False
    
    def to_dict(self) -> Dict:
        return {
            'event_id': self.event_id,
            'name': self.name,
            'event_type': self.event_type,
            'description': self.description,
            'causes': self.causes,
            'affected_entities': self.affected_entities,
            'expected_consequences': self.expected_consequences,
            'generation': self.generation,
            'resolved': self.resolved,
        }


class WorldSimulator:
    """
    Proactive world simulation engine.
    
    Detects tensions in world state and generates events proactively,
    rather than waiting for external triggers.
    """
    
    TENSION_THRESHOLDS = {
        'power_imbalance': 0.3,
        'conflict_intensity': 0.7,
        'population_pressure': 0.8,
        'resource_scarcity': 0.4,
        'unresolved_events': 5,
    }
    
    def __init__(
        self,
        graph: 'KnowledgeGraph',
        generation: int = 0,
        random_seed: int = None
    ):
        self.graph = graph
        self.generation = generation
        
        if random_seed:
            random.seed(random_seed)
        
        self.detected_tensions: List[Tension] = []
        self.pending_cascades: List[CascadeStep] = []
        self.event_history: List[SimulatedEvent] = []
    
    def step(self) -> Dict[str, Any]:
        """
        Execute one simulation step.
        
        Returns:
            Dict with tensions, events generated, and cascades resolved
        """
        result = {
            'generation': self.generation,
            'tensions_detected': [],
            'events_generated': [],
            'cascades_resolved': [],
        }
        
        self.detected_tensions = self.detect_tensions()
        result['tensions_detected'] = [t.to_dict() for t in self.detected_tensions]
        
        for tension in self.detected_tensions:
            if tension.severity >= 0.5:
                events = self.generate_events_from_tension(tension)
                result['events_generated'].extend([e.to_dict() for e in events])
                self.event_history.extend(events)
        
        resolved = self.resolve_cascades()
        result['cascades_resolved'] = [c.to_dict() for c in resolved]
        
        self.generation += 1
        
        return result
    
    def detect_tensions(self) -> List[Tension]:
        """Detect all types of tensions in the world state."""
        tensions = []
        
        tensions.extend(self._detect_power_imbalances())
        tensions.extend(self._detect_territorial_disputes())
        tensions.extend(self._detect_ideological_conflicts())
        tensions.extend(self._detect_resource_scarcity())
        tensions.extend(self._detect_pending_conflicts())
        tensions.extend(self._detect_unresolved_events())
        
        tensions.sort(key=lambda t: t.severity, reverse=True)
        
        return tensions
    
    def _detect_power_imbalances(self) -> List[Tension]:
        """Detect power imbalance tensions between factions."""
        tensions = []
        
        factions = self.graph.list_nodes(node_type='faction')
        if len(factions) < 2:
            return tensions
        
        power_levels = {}
        for faction in factions:
            power = faction.properties.get('power_level', 0.5)
            power_levels[faction.id] = power
        
        sorted_factions = sorted(power_levels.items(), key=lambda x: x[1], reverse=True)
        
        if len(sorted_factions) >= 2:
            top_power = sorted_factions[0][1]
            second_power = sorted_factions[1][1]
            
            if top_power - second_power > self.TENSION_THRESHOLDS['power_imbalance']:
                dominant_id = sorted_factions[0][0]
                tensions.append(Tension(
                    tension_id=f"tension_power_{dominant_id[:8]}",
                    tension_type=TensionType.POWER_IMBALANCE,
                    description=f"Significant power imbalance with dominant faction",
                    entities_involved=[f[0] for f in sorted_factions[:3]],
                    severity=top_power - second_power,
                    contributing_factors=[
                        f"Dominant faction power: {top_power:.2f}",
                        f"Second faction power: {second_power:.2f}",
                    ],
                    potential_events=[
                        "coalition_formation",
                        "resistance_movement",
                        "hegemonic_consolidation",
                    ],
                ))
        
        return tensions
    
    def _detect_territorial_disputes(self) -> List[Tension]:
        """Detect territorial disputes."""
        tensions = []
        
        locations = self.graph.list_nodes(node_type='location')
        faction_nodes = self.graph.list_nodes(node_type='faction')
        
        for location in locations:
            controlling_factions = []
            
            for faction in faction_nodes:
                edges = self.graph.get_edges(
                    faction.id,
                    edge_types=['controls', 'contains', 'claims'],
                    direction='out'
                )
                
                for edge in edges:
                    if edge.target_id == location.id:
                        controlling_factions.append({
                            'faction_id': faction.id,
                            'strength': edge.weight or 0.5,
                        })
            
            if len(controlling_factions) > 1:
                tensions.append(Tension(
                    tension_id=f"tension_territory_{location.id[:8]}",
                    tension_type=TensionType.TERRITORIAL_DISPUTE,
                    description=f"Multiple factions contesting {location.properties.get('name', location.id)}",
                    entities_involved=[f['faction_id'] for f in controlling_factions] + [location.id],
                    severity=max(f['strength'] for f in controlling_factions),
                    contributing_factors=[
                        f"Contested by {len(controlling_factions)} factions",
                    ],
                    potential_events=[
                        "territorial_conflict",
                        "negotiation",
                        "forced_relocation",
                    ],
                ))
        
        return tensions
    
    def _detect_ideological_conflicts(self) -> List[Tension]:
        """Detect ideological conflicts between factions."""
        tensions = []
        
        opposing_ideologies = [
            ('order', 'chaos'),
            ('traditional', 'progressive'),
            ('isolationist', 'expansionist'),
            ('collectivist', 'individualist'),
        ]
        
        factions = self.graph.list_nodes(node_type='faction')
        
        for i, faction_a in enumerate(factions):
            ideology_a = faction_a.properties.get('ideology', '').lower()
            
            for faction_b in factions[i+1:]:
                ideology_b = faction_b.properties.get('ideology', '').lower()
                
                for opp_a, opp_b in opposing_ideologies:
                    if opp_a in ideology_a and opp_b in ideology_b:
                        tensions.append(Tension(
                            tension_id=f"tension_ideology_{faction_a.id[:4]}_{faction_b.id[:4]}",
                            tension_type=TensionType.IDEOLOGICAL_CONFLICT,
                            description=f"Ideological conflict: {ideology_a} vs {ideology_b}",
                            entities_involved=[faction_a.id, faction_b.id],
                            severity=0.6,
                            contributing_factors=[
                                f"Faction A ideology: {ideology_a}",
                                f"Faction B ideology: {ideology_b}",
                            ],
                            potential_events=[
                                "ideological_war",
                                "philosophical_debate",
                                "cultural_schism",
                            ],
                        ))
        
        return tensions
    
    def _detect_resource_scarcity(self) -> List[Tension]:
        """Detect resource scarcity tensions."""
        tensions = []
        
        species_nodes = self.graph.list_nodes(node_type='species')
        
        for species in species_nodes:
            population = species.properties.get('population', 0)
            territory = species.properties.get('territory_size', 1)
            
            if territory > 0:
                density = population / territory
                
                if density > 100:
                    tensions.append(Tension(
                        tension_id=f"tension_resource_{species.id[:8]}",
                        tension_type=TensionType.RESOURCE_SCARCITY,
                        description=f"Resource pressure for {species.properties.get('name', species.id)}",
                        entities_involved=[species.id],
                        severity=min(1.0, density / 100),
                        contributing_factors=[
                            f"Population density: {density:.1f}",
                            f"Population: {population}",
                            f"Territory: {territory}",
                        ],
                        potential_events=[
                            "migration",
                            "resource_war",
                            "population_collapse",
                        ],
                    ))
        
        return tensions
    
    def _detect_pending_conflicts(self) -> List[Tension]:
        """Detect pending conflicts from relationship tensions."""
        tensions = []
        
        all_edges = []
        
        for node in self.graph.list_nodes():
            edges = self.graph.get_edges(node.id, edge_types=['conflict'])
            all_edges.extend(edges)
        
        high_tension_conflicts = [
            e for e in all_edges
            if e.weight and e.weight >= self.TENSION_THRESHOLDS['conflict_intensity']
        ]
        
        unique_conflicts = set()
        for edge in high_tension_conflicts:
            pair = tuple(sorted([edge.source_id, edge.target_id]))
            if pair not in unique_conflicts:
                unique_conflicts.add(pair)
                
                tensions.append(Tension(
                    tension_id=f"tension_conflict_{pair[0][:4]}_{pair[1][:4]}",
                    tension_type=TensionType.PENDING_CONFLICT,
                    description=f"High tension conflict between entities",
                    entities_involved=[edge.source_id, edge.target_id],
                    severity=edge.weight or 0.5,
                    contributing_factors=[
                        f"Conflict intensity: {edge.weight:.2f}",
                        edge.context or "No context provided",
                    ],
                    potential_events=[
                        "open_warfare",
                        "negotiated_settlement",
                        "skirmish",
                    ],
                ))
        
        return tensions
    
    def _detect_unresolved_events(self) -> List[Tension]:
        """Detect unresolved events causing tension."""
        tensions = []
        
        events = self.graph.list_nodes(node_type='event')
        
        unresolved = []
        for event in events:
            resolved = event.properties.get('resolved', False)
            significance = event.properties.get('significance', 0.5)
            
            if not resolved and significance > 0.3:
                unresolved.append(event)
        
        if len(unresolved) >= self.TENSION_THRESHOLDS['unresolved_events']:
            tensions.append(Tension(
                tension_id="tension_unresolved_events",
                tension_type=TensionType.UNRESOLVED_EVENT,
                description=f"{len(unresolved)} unresolved events creating world tension",
                entities_involved=[e.id for e in unresolved[:5]],
                severity=len(unresolved) / 20,
                contributing_factors=[
                    f"Unresolved event count: {len(unresolved)}",
                ],
                potential_events=[
                    "crisis_point",
                    "mass_resolution",
                    "cascading_consequences",
                ],
            ))
        
        return tensions
    
    def generate_events_from_tension(self, tension: Tension) -> List[SimulatedEvent]:
        """Generate events to address a tension."""
        events = []
        
        event_type = random.choice(tension.potential_events)
        
        event = self._create_event_for_tension(tension, event_type)
        if event:
            events.append(event)
            
            cascade_steps = self._create_cascade_steps(event)
            self.pending_cascades.extend(cascade_steps)
        
        return events
    
    def _create_event_for_tension(
        self,
        tension: Tension,
        event_type: str
    ) -> Optional[SimulatedEvent]:
        """Create a specific event for a tension."""
        event_id = f"event_{event_type}_{datetime.utcnow().timestamp():.0f}"
        
        event_templates = {
            'coalition_formation': {
                'name': 'Coalition Forms',
                'description': 'Weaker factions unite against dominant power',
            },
            'resistance_movement': {
                'name': 'Resistance Movement',
                'description': 'Underground resistance forms against hegemony',
            },
            'territorial_conflict': {
                'name': 'Territorial Conflict',
                'description': 'Armed conflict over contested territory',
            },
            'ideological_war': {
                'name': 'Ideological War',
                'description': 'Conflict driven by opposing beliefs',
            },
            'migration': {
                'name': 'Mass Migration',
                'description': 'Population moves seeking resources',
            },
            'resource_war': {
                'name': 'Resource War',
                'description': 'Conflict over scarce resources',
            },
            'open_warfare': {
                'name': 'Open Warfare',
                'description': 'High tension erupts into open conflict',
            },
            'crisis_point': {
                'name': 'World Crisis',
                'description': 'Multiple unresolved events trigger crisis',
            },
        }
        
        template = event_templates.get(event_type, {
            'name': f'Event: {event_type}',
            'description': f'Event generated from {tension.tension_type.value}',
        })
        
        return SimulatedEvent(
            event_id=event_id,
            name=template['name'],
            event_type=event_type,
            description=template['description'],
            causes=[tension.tension_id],
            affected_entities=tension.entities_involved,
            expected_consequences=self._predict_consequences(event_type, tension),
            generation=self.generation,
        )
    
    def _predict_consequences(
        self,
        event_type: str,
        tension: Tension
    ) -> List[str]:
        """Predict consequences of an event."""
        consequence_map = {
            'coalition_formation': [
                'Power balance shifts',
                'New alliance edges created',
                'Trust changes between factions',
            ],
            'resistance_movement': [
                'Underground network forms',
                'Sabotage events possible',
                'Spy relationships emerge',
            ],
            'territorial_conflict': [
                'Territory control changes',
                'Population displacement',
                'Resource access shifts',
            ],
            'migration': [
                'Population redistribution',
                'New location relationships',
                'Cultural mixing',
            ],
            'open_warfare': [
                'Multiple conflict edges',
                'Power levels change',
                'Possible faction destruction',
            ],
        }
        
        return consequence_map.get(event_type, [
            'Status quo disrupted',
            'Relationships change',
        ])
    
    def _create_cascade_steps(self, event: SimulatedEvent) -> List[CascadeStep]:
        """Create cascade steps for an event's consequences."""
        steps = []
        
        for i, consequence in enumerate(event.expected_consequences):
            cascade_event_id = f"cascade_{event.event_id}_{i}"
            
            steps.append(CascadeStep(
                step_id=f"step_{event.event_id}_{i}",
                trigger_event_id=event.event_id,
                resulting_event_id=cascade_event_id,
                propagation_type='consequence',
                affected_entities=event.affected_entities[:],
                delay_generations=random.randint(1, 3),
            ))
        
        return steps
    
    def resolve_cascades(self) -> List[CascadeStep]:
        """Resolve pending cascade steps that are ready."""
        resolved = []
        
        ready_steps = [
            s for s in self.pending_cascades
            if s.delay_generations <= 0 and not s.resolved
        ]
        
        for step in ready_steps:
            self._execute_cascade_step(step)
            step.resolved = True
            resolved.append(step)
        
        for step in self.pending_cascades:
            if not step.resolved:
                step.delay_generations -= 1
        
        self.pending_cascades = [
            s for s in self.pending_cascades
            if not s.resolved
        ]
        
        return resolved
    
    def _execute_cascade_step(self, step: CascadeStep):
        """Execute a cascade step, updating the graph."""
        for entity_id in step.affected_entities:
            entity = self.graph.get_node(entity_id)
            if not entity:
                continue
            
            if entity.type == 'faction':
                current_power = entity.properties.get('power_level', 0.5)
                change = random.uniform(-0.1, 0.1)
                self.graph.update_node(entity_id, {
                    'power_level': max(0.1, min(1.0, current_power + change)),
                })
            
            elif entity.type == 'species':
                current_pop = entity.properties.get('population', 100)
                change_factor = random.uniform(0.9, 1.1)
                self.graph.update_node(entity_id, {
                    'population': max(0, int(current_pop * change_factor)),
                })
        
        try:
            self.graph.add_node(
                node_type='event',
                properties={
                    'name': f"Cascade: {step.propagation_type}",
                    'event_type': 'cascade',
                    'description': f"Consequence of {step.trigger_event_id}",
                    'generation': self.generation,
                },
                tags=['cascade', 'generated'],
                source='world_simulator',
                node_id=step.resulting_event_id,
            )
        except:
            pass
    
    def store_event_in_graph(self, event: SimulatedEvent) -> str:
        """Store a simulated event in the knowledge graph."""
        event_id = self.graph.add_node(
            node_type='event',
            properties={
                'name': event.name,
                'event_type': event.event_type,
                'description': event.description,
                'generation': event.generation,
                'resolved': event.resolved,
            },
            tags=['simulated', 'world_event'],
            source='world_simulator',
            node_id=event.event_id,
        )
        
        for entity_id in event.affected_entities:
            self.graph.add_edge(
                source_id=event_id,
                target_id=entity_id,
                edge_type='references',
                weight=event.severity if hasattr(event, 'severity') else 0.5,
                context=event.event_type,
            )
        
        return event_id
    
    def get_world_state_summary(self) -> Dict[str, Any]:
        """Get summary of current world state."""
        return {
            'generation': self.generation,
            'total_tensions': len(self.detected_tensions),
            'high_severity_tensions': len([t for t in self.detected_tensions if t.severity > 0.7]),
            'pending_cascades': len(self.pending_cascades),
            'events_generated': len(self.event_history),
            'tension_breakdown': {
                ttype: len([t for t in self.detected_tensions if t.tension_type == ttype])
                for ttype in TensionType
            },
        }
